services:
  arch-wine-fs22:
    image: toetje585/arch-wine-fs22:latest
    container_name: arch-wine-fs22
    environment:
      - VNC_PASSWORD=<your vnc password>
      - PUID=<UID from user>
      - PGID=<UID from user>
      - WEB_USERNAME=<dedicated server portal username>
      - WEB_PASSWORD=<dedicated server portal password>
      - SERVER_NAME=<your server name>
      - SERVER_PASSWORD=<your game join password>
      - SERVER_ADMIN=<your server admin password>
      - SERVER_PLAYERS=16
      - SERVER_PORT=10823
      - SERVER_REGION=en
      - SERVER_MAP=MapUS
      - SERVER_DIFFICULTY=3
      - SERVER_PAUSE=2
      - SERVER_SAVE_INTERVAL=180.000000
      - SERVER_STATS_INTERVAL=31536000
      - SERVER_CROSSPLAY=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fs22/config:/opt/fs22/config
      - /opt/fs22/game:/opt/fs22/game
      - /opt/fs22/installer:/opt/fs22/installer
    ports:
      - 5900:5900/tcp
      - 8080:8080/tcp
      - 10823:10823/tcp
      - 10823:10823/udp
    cap_add:
      - SYS_NICE
    restart: unless-stopped
